### ISSUE TITLE
Avoid PROGRAM ABORT: No instrumentation detected

### ISSUE THREAD

**Issue by LimitedResults** [mxmssh/drAFL#5]
Hello,

nice project man, thank you!
Just to avoid this kind of error (if other people are in trouble).
[-] PROGRAM ABORT : No instrumentation detected
         Location : perform_dry_run(), afl-fuzz.c:2860

I have replaced -m 500 by -m none
Typically:
../afl/afl-fuzz -m none -i ./in/ -o out ./afl_test

and then it runs. (please close the issue)
Regards
LR

**Comment by mxmssh** [comment]
Hey, thank you! I will update the description.
